# Generated by Django 2.2.19 on 2022-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тэга')),
                ('color', models.CharField(default='#ffffff', max_length=7, unique=True, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор тэга')),
            ],
        ),
    ]
