# Generated by Django 2.2.19 on 2022-09-23 15:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет тэга'),
        ),
    ]
